# Generated by Django 5.0.2 on 2024-03-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litereview', '0002_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=9999),
        ),
    ]
