# pylint: skip-file
# Generated by Django 5.0.2 on 2024-03-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litereview', '0004_alter_review_rating_alter_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('In Progress', 'In Progress'), ('Dropped', 'Dropped')], max_length=128),
        ),
    ]
