# pylint: skip-file
# Generated by Django 5.0.2 on 2024-03-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litereview', '0005_alter_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='media_type',
            field=models.CharField(choices=[('MOV', 'Movie'), ('BOK', 'Book'), ('MGA', 'Manga'), ('TVS', 'TV'), ('MUS', 'Music'), ('COM', 'Comic/Graphic Novel'), ('VGA', 'Video Game'), ('POD', 'Podcast')], default='MOV', max_length=3),
        ),
    ]
